### ISSUE TITLE
ArrayIndexOutOfBoundsException in 1.3.2

### ISSUE THREAD

**Issue by mars-lan** [bartgryszko/react-native-circular-progress#213]
Start seeing this exception in Android after upgrading from 1.3.0 to 1.3.2. Verified on `react-native-svg` 9.11.1 & 9.12.0.

```
java.lang.ArrayIndexOutOfBoundsException
        at android.graphics.DashPathEffect.<init>(DashPathEffect.java:36)
        at com.horcrux.svg.RenderableView.setupStrokePaint(RenderableView.java:454)
        at com.horcrux.svg.RenderableView.draw(RenderableView.java:367)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:102)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:102)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:302)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:253)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:104)
```

**Comment by CantFayle** [comment]
I'm also having this issue with version 1.3.2 - I'm using ejected expo but stack trace is similar

**Comment by JacopoKenzo** [comment]
Same problem here updating from 1.3.0 to 1.3.2 - only on Android

**Comment by cyqui** [comment]
The following fixes it : 
             strokeDasharray={Object.values(dashedBackgroundStyle)}

dashedBackgroundStyle is supposed to be an array. It's an object.

in src/CircularProgress.js
